version: '3.8'

services:
  database:
    image: postgres:17
    container_name: prototipo_tcc_database_container
    restart: always
    environment:
      POSTGRES_USER: prototipo_tcc_user
      POSTGRES_PASSWORD: teste123
      POSTGRES_DB: prototipo_tcc_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - prototipo_tcc_data:/var/lib/postgresql/data
    networks:
      - prototipo_tcc_network


  analytics_database:
    image: postgres:17
    container_name: prototipo_tcc_analytics_database_container
    restart: always
    environment:
      POSTGRES_USER: prototipo_tcc_user
      POSTGRES_PASSWORD: teste123
      POSTGRES_DB: prototipo_tcc_analytics_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5433:5433"
    volumes:
      - prototipo_tcc_analytics_data:/var/lib/postgresql/data
    networks:
      - prototipo_tcc_network

  web:
    build:
      context: ./prototipo-tcc-back
      dockerfile: Dockerfile
    container_name: prototipo_tcc_web_container
    restart: unless-stopped
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_MAX_THREADS: 5
      PLUMBER_URL: "http://host.docker.internal:8000/gerar_grafico"
      DATABASE_URL: postgresql://prototipo_tcc_user:teste123@database:5432/prototipo_tcc_db
      PORT: 3000
    volumes:
      - ./prototipo-tcc-back:/rails
    depends_on:
      database:
        condition: service_healthy
    networks:
      - prototipo_tcc_network
      
  airflow_postgres:
    image: postgres:15
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    networks:
      - prototipo_tcc_network

  airflow-init:
    image: apache/airflow:2.8.2
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db upgrade &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname Airflow \
          --lastname Admin \
          --role Admin \
          --email admin@example.com
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}"
    volumes:
      - ./airflow:/opt/airflow
    networks:
      - prototipo_tcc_network

  airflow-webserver:
    image: apache/airflow:2.8.2
    container_name: airflow_webserver
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      airflow_postgres:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: "${AIRFLOW__CORE__EXECUTOR}"
      AIRFLOW__CORE__FERNET_KEY: "${AIRFLOW__CORE__FERNET_KEY}"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}"
      AIRFLOW_CONN_POSTGRES_SOURCE: "${AIRFLOW_CONN_POSTGRES_SOURCE}"
      AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS: "false"
      AIRFLOW_CONN_POSTGRES_ANALYTICS: "${AIRFLOW_CONN_POSTGRES_ANALYTICS}"
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow webserver
    networks:
      - prototipo_tcc_network

  airflow-scheduler:
    image: apache/airflow:2.8.2
    container_name: airflow_scheduler
    restart: always
    depends_on:
      airflow-webserver:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: "${AIRFLOW__CORE__EXECUTOR}"
      AIRFLOW__CORE__FERNET_KEY: "${AIRFLOW__CORE__FERNET_KEY}"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}"
      AIRFLOW_CONN_POSTGRES_SOURCE: "${AIRFLOW_CONN_POSTGRES_SOURCE}"
      AIRFLOW_CONN_POSTGRES_ANALYTICS: "${AIRFLOW_CONN_POSTGRES_ANALYTICS}"
    volumes:
      - ./airflow:/opt/airflow
    command: airflow scheduler
    networks:
      - prototipo_tcc_network

volumes:
  prototipo_tcc_data:
  prototipo_tcc_analytics_data:
  airflow_postgres_data:

networks:
  prototipo_tcc_network:
    driver: bridge
