version: "3.8"

services:
  database:
    image: postgres:17
    container_name: prototipo_tcc_database_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - prototipo_tcc_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./prototipo-tcc-back
      dockerfile: Dockerfile
    container_name: prototipo_tcc_backend
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DB_HOST: database
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}"
      PGHOST: database
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "3000:80"
  frontend:
    build: ./prototipo-tcc-front
    ports:
      - "4200:4200"
  # analysis_api:
  #   build:
  #     context: "./Scripts R"
  #     dockerfile: Dockerfile
  #   container_name: prototipo_tcc_analysis_api
  #   ports:
  #     - "8000:8000"
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
volumes:
  prototipo_tcc_data:
    driver: local